# Generated by Django 4.1.1 on 2022-11-12 14:49

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Estoque", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manutenção",
            name="comentario",
        ),
        migrations.RemoveField(
            model_name="manutenção",
            name="descricao_executado",
        ),
        migrations.AddField(
            model_name="manutenção",
            name="servico_executado",
            field=models.CharField(
                default=2, max_length=1024, verbose_name="Serviço executado"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="manutenção",
            name="ganho",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                default_currency="USD",
                max_digits=11,
                verbose_name="Economizado",
            ),
        ),
        migrations.AlterField(
            model_name="manutenção",
            name="ordem",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Ordem de Serviço"
            ),
        ),
    ]
