# Generated by Django 4.1.1 on 2022-11-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Estoque", "0002_remove_manutenção_comentario_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Equipamentos",
            new_name="Equipamento",
        ),
    ]
