# Generated by Django 4.1.1 on 2022-11-12 17:50

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("Estoque", "0005_remove_manutenção_field_name_manutenção_imagem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manutenção",
            options={"verbose_name_plural": "Manutenções"},
        ),
        migrations.AddField(
            model_name="equipamento",
            name="imagem",
            field=models.ImageField(
                default=1, upload_to=None, verbose_name="Foto do equipamento"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="manutenção",
            name="custo_real",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=(("USD", "Dolar"), ("BRL", "Real")),
                decimal_places=2,
                default=Decimal("0"),
                default_currency="BRL",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="manutenção",
            name="custo_real_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "Dolar"), ("BRL", "Real")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="manutenção",
            name="custo_reparo",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=(("USD", "Dolar"), ("BRL", "Real")),
                decimal_places=2,
                default_currency="BRL",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="manutenção",
            name="custo_reparo_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "Dolar"), ("BRL", "Real")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="manutenção",
            name="ganho",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                currency_choices=(("USD", "Dolar"), ("BRL", "Real")),
                decimal_places=2,
                default_currency="BRL",
                max_digits=11,
                null=True,
                verbose_name="Economizado",
            ),
        ),
        migrations.AlterField(
            model_name="manutenção",
            name="ganho_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("USD", "Dolar"), ("BRL", "Real")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
