# Generated by Django 4.1.1 on 2022-11-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Estoque", "0006_alter_manutenção_options_equipamento_imagem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipamento",
            name="imagem",
        ),
    ]
