# Generated by Django 4.1.1 on 2022-11-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Estoque", "0007_remove_equipamento_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manutenção",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=None,
                verbose_name="Foto do equipamento",
            ),
        ),
    ]
