# Generated by Django 4.1.3 on 2022-11-19 15:37

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Estoque', '0008_alter_manutenção_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutenção',
            name='custo_real_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar'), ('BRL', 'Real')], default='BRL', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='manutenção',
            name='custo_reparo_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar'), ('BRL', 'Real')], default='BRL', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='manutenção',
            name='ganho_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'Dolar'), ('BRL', 'Real')], default='BRL', editable=False, max_length=3),
        ),
    ]
