# Generated by Django 4.1.3 on 2022-11-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0005_remove_luva_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="luva",
            name="status_exame",
            field=models.BooleanField(
                choices=[(True, True), (False, False)],
                default=True,
                verbose_name="Status do Exame",
            ),
            preserve_default=False,
        ),
    ]
