# Generated by Django 4.1.3 on 2022-11-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0006_luva_status_exame"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Luva",
        ),
    ]
