# Generated by Django 4.1.3 on 2022-11-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0007_delete_luva"),
    ]

    operations = [
        migrations.CreateModel(
            name="Luva",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "n_serie",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Nº de Série"
                    ),
                ),
                (
                    "lado",
                    models.CharField(
                        choices=[("Esquerda", "Esquerda"), ("Direita", "Direita")],
                        default="Esquerda",
                        max_length=20,
                    ),
                ),
                (
                    "status_exame",
                    models.BooleanField(
                        choices=[(True, True), (False, False)],
                        verbose_name="Status do Exame",
                    ),
                ),
                ("ultimo_exame", models.DateField()),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Luva",
                        to="NR10.eletricista",
                    ),
                ),
            ],
        ),
    ]
