# Generated by Django 4.1.3 on 2022-11-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0008_luva"),
    ]

    operations = [
        migrations.AddField(
            model_name="eletricista",
            name="id_ambev",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="ID Ambev"
            ),
        ),
        migrations.AlterField(
            model_name="luva",
            name="status_exame",
            field=models.BooleanField(
                choices=[(True, "OK"), (False, "Inrregular")],
                verbose_name="Status do Exame",
            ),
        ),
    ]
