# Generated by Django 4.1.3 on 2022-11-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0009_eletricista_id_ambev_alter_luva_status_exame"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aso",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
                (
                    "certificado",
                    models.FileField(max_length=254, upload_to="NR10/ASO/"),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Aso",
                        to="NR10.eletricista",
                    ),
                ),
            ],
            options={
                "verbose_name": "ASO",
                "verbose_name_plural": "ASO's",
            },
        ),
        migrations.RenameField(
            model_name="autorizacao",
            old_name="certificado",
            new_name="documento",
        ),
        migrations.AlterField(
            model_name="autorizacao",
            name="nivel",
            field=models.CharField(
                choices=[
                    (
                        "Sistema desernegizado sob supervisão",
                        "Sistema desernegizado sob supervisão",
                    ),
                    ("Sistema desernegizado", "Sistema desernegizado"),
                    (
                        "Sistema ernegizado Baixa tensão",
                        "Sistema ernegizado Baixa tensão",
                    ),
                    (
                        "Sistema ernegizado Alta tensão",
                        "Sistema ernegizado Alta tensão",
                    ),
                ],
                default="Sistema desernegizado",
                max_length=254,
            ),
        ),
        migrations.DeleteModel(
            name="Asu",
        ),
    ]
