# Generated by Django 4.1.3 on 2022-12-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0011_alter_autorizacao_nivel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capacete",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "n_serie",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Nº de Série"
                    ),
                ),
                (
                    "status_exame",
                    models.BooleanField(
                        choices=[(True, "OK"), (False, "Inrregular")],
                        verbose_name="Status do Exame",
                    ),
                ),
                ("ultimo_exame", models.DateField()),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Capacete",
                        to="NR10.eletricista",
                    ),
                ),
            ],
        ),
    ]
