# Generated by Django 4.1.3 on 2022-12-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0012_capacete"),
    ]

    operations = [
        migrations.CreateModel(
            name="Roupa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "n_serie",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Nº de Série"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("Calça", "Calça"), ("Camisa", "Camisa")],
                        default="Camisa",
                        max_length=20,
                        verbose_name="Tipo de Roupa",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Roupa",
                        to="NR10.eletricista",
                    ),
                ),
            ],
        ),
    ]
