# Generated by Django 4.1.3 on 2022-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0013_roupa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="eletricista",
            name="id",
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="eletricista",
            name="nome",
            field=models.CharField(max_length=30),
        ),
    ]
