# Generated by Django 4.1.3 on 2022-12-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0014_extra_alter_eletricista_id_alter_eletricista_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eletricista",
            name="id_ambev",
        ),
        migrations.AlterField(
            model_name="eletricista",
            name="nome",
            field=models.CharField(max_length=60),
        ),
    ]
