# Generated by Django 4.1.3 on 2022-12-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0015_remove_eletricista_id_ambev_alter_eletricista_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="aso",
            name="status_exame",
            field=models.BooleanField(default=1, verbose_name="Status do Exame"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="aso",
            name="certificado",
            field=models.FileField(
                blank=True, max_length=254, null=True, upload_to="NR10/ASO/"
            ),
        ),
        migrations.AlterField(
            model_name="nr10",
            name="certificado",
            field=models.FileField(
                blank=True, max_length=254, null=True, upload_to="NR10/NR10/"
            ),
        ),
        migrations.AlterField(
            model_name="nr10complementar",
            name="certificado",
            field=models.FileField(
                blank=True,
                max_length=254,
                null=True,
                upload_to="NR10/NR10Complementar/",
            ),
        ),
    ]
