# Generated by Django 4.1.1 on 2022-11-18 14:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saq.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utils", "0009_alter_anotacao_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitacaoProblema",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=80)),
                ("item", models.CharField(max_length=80)),
                (
                    "descricao",
                    models.CharField(blank=True, default=" ", max_length=1024),
                ),
                (
                    "create_at",
                    saq.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utils.area",
                    ),
                ),
            ],
        ),
    ]
