# Generated by Django 4.1.3 on 2022-11-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("saq", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digitacaoproblema",
            name="descricao",
            field=models.TextField(blank=True, default=" ", max_length=1024),
        ),
    ]
