# Generated by Django 4.1.3 on 2022-11-21 12:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import saq.models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0009_alter_anotacao_author"),
        ("saq", "0002_alter_digitacaoproblema_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="SugestaoMelhora",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=80)),
                (
                    "id_ambev",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ID Ambev"
                    ),
                ),
                (
                    "contribuicao",
                    models.TextField(max_length=1024, verbose_name="Contribuição"),
                ),
                (
                    "sugestao",
                    models.TextField(max_length=1024, verbose_name="Sugestão"),
                ),
                (
                    "create_at",
                    saq.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utils.area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sugestão de Melhora",
                "verbose_name_plural": "Sugestões de Melhora",
            },
        ),
    ]
