# Generated by Django 4.1.3 on 2022-11-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("saq", "0003_sugestaomelhora"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sugestaomelhora",
            options={"verbose_name": "Sugestão", "verbose_name_plural": "Sugestões"},
        ),
    ]
