# Generated by Django 4.1.3 on 2022-11-23 18:04

from django.db import migrations, models
import django.utils.timezone
import saq.models


class Migration(migrations.Migration):

    dependencies = [
        ("saq", "0004_alter_sugestaomelhora_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apresentacao",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=80)),
                (
                    "pdf",
                    models.FileField(max_length=254, upload_to="saq/apresentacao/"),
                ),
                (
                    "edited_at",
                    saq.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "Apresentação",
                "verbose_name_plural": "Apresentações",
            },
        ),
    ]
