# Generated by Django 4.1.1 on 2022-10-08 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tarefas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('prioridade', models.SmallIntegerField(choices=[(1, 'Baixo'), (2, 'Medio Baixo'), (3, 'Médio'), (4, 'Alto'), (5, 'Urgente')])),
                ('prazo', models.DateField(blank=True, null=True)),
                ('situacao', models.SmallIntegerField(choices=[(1, 'Não Iniciado'), (2, 'Em Andamento'), (3, 'Finalizado')], default=1)),
                ('descricao', models.CharField(blank=True, max_length=1200, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', tarefas.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comentario', models.CharField(blank=True, max_length=1200, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('prioridade', models.SmallIntegerField(choices=[(1, 'Baixo'), (2, 'Medio Baixo'), (3, 'Médio'), (4, 'Alto'), (5, 'Urgente')])),
                ('inicio', models.DateField(blank=True, null=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('situacao', models.SmallIntegerField(choices=[(1, 'Não Iniciado'), (2, 'Em Andamento'), (3, 'Finalizado')], default=1)),
                ('descricao', models.CharField(blank=True, max_length=1200, null=True)),
                ('comentario', models.CharField(blank=True, max_length=1200, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinhasAnotacoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('anotacao', models.CharField(blank=True, max_length=1200, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
