# Generated by Django 4.1.1 on 2022-10-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
    ]
