# Generated by Django 4.1.1 on 2022-11-11 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tarefas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarefas', '0002_auto_20221008_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minhasanotacoes',
            name='anotacao',
            field=models.CharField(blank=True, max_length=5048, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='comentario',
            field=models.CharField(blank=True, max_length=5048, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.CharField(blank=True, max_length=5048, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='comentario',
            field=models.CharField(blank=True, max_length=5048, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.CharField(blank=True, max_length=5048, null=True),
        ),
        migrations.CreateModel(
            name='Soda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('prioridade', models.SmallIntegerField(choices=[(1, 'Baixo'), (2, 'Medio Baixo'), (3, 'Médio'), (4, 'Alto'), (5, 'Urgente')])),
                ('prazo', models.DateField(blank=True, null=True)),
                ('situacao', models.SmallIntegerField(choices=[(1, 'Não Iniciado'), (2, 'Em Andamento'), (3, 'Finalizado')], default=1)),
                ('descricao', models.CharField(blank=True, max_length=5048, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', tarefas.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comentario', models.CharField(blank=True, max_length=5048, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
