# Generated by Django 4.1.1 on 2022-11-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_rename_minhasanotacoes_d_soda_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soda',
            name='prioridade',
        ),
    ]
