# Generated by Django 4.1.1 on 2022-11-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0007_alter_soda_comentario_alter_soda_descricao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="soda",
            old_name="situacao",
            new_name="status",
        ),
        migrations.AlterField(
            model_name="soda",
            name="comentario",
            field=models.CharField(blank=True, default=" ", max_length=5048),
        ),
        migrations.AlterField(
            model_name="soda",
            name="descricao",
            field=models.CharField(blank=True, default=" ", max_length=5048),
        ),
    ]
