# Generated by Django 4.1.1 on 2022-11-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0008_rename_situacao_soda_status_alter_soda_comentario_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="soda",
            options={"verbose_name_plural": "SODA"},
        ),
    ]
