# Generated by Django 4.1.1 on 2022-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0009_alter_soda_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarefa",
            name="comentario",
            field=models.CharField(blank=True, default="", max_length=5048, null=True),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="descricao",
            field=models.CharField(blank=True, default="", max_length=5048, null=True),
        ),
    ]
