# Generated by Django 4.1.1 on 2022-11-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0010_alter_tarefa_comentario_alter_tarefa_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soda",
            name="comentario",
            field=models.CharField(blank=True, default=" ", max_length=70),
        ),
    ]
