# Generated by Django 4.1.3 on 2022-11-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0011_alter_soda_comentario"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="documento",
            field=models.FileField(
                blank=True, max_length=254, null=True, upload_to="Tarefas/tarefa/"
            ),
        ),
    ]
