# Generated by Django 4.1.3 on 2022-12-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0013_produtividade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtividade",
            name="comentario",
            field=models.CharField(blank=True, default=" ", max_length=70),
        ),
    ]
