# Generated by Django 4.1.3 on 2022-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tarefas", "0014_alter_produtividade_comentario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtividade",
            name="acao",
            field=models.CharField(max_length=80, verbose_name="Ação"),
        ),
    ]
