# Generated by Django 4.1.1 on 2022-09-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.CharField(blank=True, max_length=1200, null=True)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
