# Generated by Django 4.1.1 on 2022-11-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treinamento", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Aula",
            new_name="Referencia",
        ),
    ]
