# Generated by Django 4.1.3 on 2022-12-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treinamento", "0003_aula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencia",
            name="descricao",
            field=models.CharField(blank=True, default=" ", max_length=1200, null=True),
        ),
    ]
