# Generated by Django 4.1.3 on 2022-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treinamento", "0004_alter_referencia_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aula",
            name="nome",
            field=models.CharField(max_length=70),
        ),
    ]
