# Generated by Django 4.1.1 on 2022-11-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0006_anotacao_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anotacao",
            name="author",
        ),
    ]
