# Generated by Django 4.1.3 on 2022-11-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0009_alter_anotacao_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="anotacao",
            name="documento",
            field=models.FileField(
                blank=True, max_length=254, null=True, upload_to="Utils/anotacao/"
            ),
        ),
    ]
